"""A tool for merging downloaded ASF burst SLCs into ESA SAFEs."""

from argparse import ArgumentParser
from pathlib import Path

from burst2safe.burst2stack_utils import import_burst_infos_from_csv
from burst2safe.safe import Safe
from burst2safe.utils import BurstInfo, drop_duplicates, optional_wd


DESCRIPTION = """Merge downloaded ASF burst SLCs into ESA SAFEs.
This is the third step in the burst2stack workflow. Use the CSV file
generated by burst2stack-search command. All burst files must be
downloaded before running this command (use burst2stack-download).
"""


def validate_downloads(burst_infos: list[BurstInfo]) -> None:
    """Validate that all required files have been downloaded.

    Parameters
    ----------
    burst_infos : list[BurstInfo]
        List of BurstInfo objects.

    Raises
    ------
    ValueError
        If any required files are missing.
    """
    missing_files = []

    for info in burst_infos:
        if info.data_path is not None and not info.data_path.exists():
            missing_files.append(info.data_path)
        if not info.metadata_path.exists():
            missing_files.append(info.metadata_path)

    if missing_files:
        raise ValueError(
            f'Missing {len(missing_files)} required file(s). '
            f'Run burst2stack-download first. Missing: {", ".join([x.name for x in missing_files[:5]])}'
            + ('...' if len(missing_files) > 5 else '')
        )


def burst2stack_merge(
    input_csv: Path,
    all_anns: bool = False,
    keep_files: bool = False,
    work_dir: Path | None = None,
) -> list[Path]:
    """Merge downloaded burst SLCs into SAFEs.

    Parameters
    ----------
    input_csv : Path
        Path to the input CSV file.
    all_anns : bool, optional
        Include product annotation files for all swaths, regardless of included bursts.
        Default is False.
    keep_files : bool, optional
        Keep the intermediate files. Default is False.
    work_dir : Path | None, optional
        The directory to create the SAFE in. Default is current directory.

    Returns
    -------
    list[Path]
        List of paths to the created SAFE files.

    Raises
    ------
    FileNotFoundError
        If the input CSV file does not exist.
    ValueError
        If required files are missing or burst groups are invalid.
    """
    work_dir = optional_wd(work_dir)

    # Import burst infos from CSV
    burst_infos = import_burst_infos_from_csv(input_csv)
    print(f'Loaded {len(burst_infos)} burst(s) from {input_csv}')

    # Validate downloads
    print('Validating downloaded files...')
    validate_downloads(burst_infos)
    print('All required files are present.')

    # Group bursts by absolute orbit
    abs_orbits = drop_duplicates([bi.absolute_orbit for bi in burst_infos])
    burst_sets = [[bi for bi in burst_infos if bi.absolute_orbit == orbit] for orbit in abs_orbits]

    print(f'Creating {len(abs_orbits)} SAFE(s)...')
    safe_paths = []

    for burst_set in burst_sets:
        # Add shape info and start/stop UTC
        for info in burst_set:
            info.add_shape_info()
        for info in burst_set:
            info.add_start_stop_utc()

        # Create SAFE
        safe = Safe(burst_set, all_anns, work_dir)
        safe_path = safe.create_safe()
        safe_paths.append(safe_path)
        print(f'Created: {safe_path.name}')

        # Cleanup if requested
        if not keep_files:
            safe.cleanup()

    print(f'SAFEs created: {len(safe_paths)}')
    return safe_paths


def main() -> None:
    """Command-line entry point for burst2stack-merge."""
    parser = ArgumentParser(description=DESCRIPTION)
    parser.add_argument(
        '--input-csv',
        type=str,
        required=True,
        help='Input CSV file path (generated by burst2stack-search)',
    )
    parser.add_argument(
        '--all-anns',
        action='store_true',
        default=False,
        help='Include product annotation files for all swaths, regardless of included bursts.',
    )
    parser.add_argument(
        '--keep-files',
        action='store_true',
        default=False,
        help='Keep the intermediate files',
    )
    parser.add_argument(
        '--output-dir',
        type=str,
        default=None,
        help='Output directory to create SAFEs in',
    )

    args = parser.parse_args()

    burst2stack_merge(
        input_csv=Path(args.input_csv),
        all_anns=args.all_anns,
        keep_files=args.keep_files,
        work_dir=Path(args.output_dir) if args.output_dir else None,
    )


if __name__ == '__main__':
    main()
