"""A tool for downloading ASF burst SLCs from a CSV file."""

import logging
from argparse import ArgumentParser
from pathlib import Path

from data_downloader import downloader

from burst2safe.burst2stack_utils import import_burst_infos_from_csv
from burst2safe.utils import BurstInfo

logger = logging.getLogger(__name__)


DESCRIPTION = """Download ASF burst SLCs from a CSV file.
This is the second step in the burst2stack workflow. Use the CSV file
generated by burst2stack-search command.

Features:
- Supports resume: already downloaded files are skipped
- Uses data-downloader library with browser cookie authorization
"""


def get_download_tasks(
    burst_infos: list[BurstInfo],
    force: bool = False,
) -> tuple[list[str], list[Path]]:
    """Get download tasks from burst infos.

    Parameters
    ----------
    burst_infos : list[BurstInfo]
        List of BurstInfo objects.
    force : bool, optional
        If True, download even if the file already exists. Default is False.

    Returns
    -------
    tuple[list[str], list[Path]]
        A tuple of (urls, file_paths) to download.
    """
    urls = []
    file_paths = []

    for info in burst_infos:
        # Data file
        if info.data_path is not None and info.data_url is not None:
            if force or not info.data_path.exists():
                urls.append(info.data_url)
                file_paths.append(info.data_path)

        # Metadata file
        if info.metadata_url is not None:
            if force or not info.metadata_path.exists():
                urls.append(info.metadata_url)
                file_paths.append(info.metadata_path)

    return urls, file_paths


def burst2stack_download(
    input_csv: Path,
    force: bool = False,
) -> None:
    """Download ASF burst SLCs from a CSV file.

    Parameters
    ----------
    input_csv : Path
        Path to the input CSV file.
    force : bool, optional
        If True, force re-download even if files exist. Default is False.

    Raises
    ------
    FileNotFoundError
        If the input CSV file does not exist.
    ValueError
        If some downloads failed.
    """
    # Import burst infos from CSV
    burst_infos = import_burst_infos_from_csv(input_csv)
    print(f'Loaded {len(burst_infos)} burst(s) from {input_csv}')

    # Get download tasks
    urls, file_paths = get_download_tasks(burst_infos, force=force)

    if not urls:
        print('All files already exist. Nothing to download.')
        return

    # Ensure parent directories exist
    for file_path in file_paths:
        file_path.parent.mkdir(parents=True, exist_ok=True)

    print(f'Downloading {len(urls)} file(s)...')

    # Convert file paths to strings for data-downloader
    file_names = [str(fp) for fp in file_paths]

    # Download using data-downloader with browser cookie authorization
    downloader.download_datas(
        urls=urls,
        folder=None,  # Use absolute paths in file_names
        file_names=file_names,
        authorize_from_browser=True,
        desc='Downloading bursts',
    )

    # Verify downloads
    missing_files = [fp for fp in file_paths if not fp.exists()]
    if missing_files:
        logger.error(f'Failed to download {len(missing_files)} file(s)')
        raise ValueError(f'Error downloading, missing files: {", ".join([x.name for x in missing_files])}')

    print('Download complete.')


def main() -> None:
    """Command-line entry point for burst2stack-download."""
    parser = ArgumentParser(description=DESCRIPTION)
    parser.add_argument(
        '--input-csv',
        type=str,
        required=True,
        help='Input CSV file path (generated by burst2stack-search)',
    )
    parser.add_argument(
        '--force',
        action='store_true',
        default=False,
        help='Force re-download even if files already exist',
    )

    args = parser.parse_args()

    burst2stack_download(
        input_csv=Path(args.input_csv),
        force=args.force,
    )


if __name__ == '__main__':
    main()
